FROM amazoncorretto:17-alpine

WORKDIR /app

# Copy Maven wrapper and POM file
COPY .mvn/ .mvn
COPY mvnw pom.xml ./

# Make the mvnw script executable
RUN chmod +x mvnw

# Download dependencies
RUN ./mvnw dependency:go-offline

# Copy source code
COPY src ./src

# Expose port 8080
EXPOSE 8080

# Run the application
CMD ["./mvnw", "spring-boot:run"]
